---
- hosts: routers
  gather_facts: no
  tasks:
    - name: Backup running configuration
      ios_command:
        commands: show running-config
      register: config

    - name: Save configuration to file
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "backup_{{ inventory_hostname }}.txt"
